### ISSUE TITLE
Failed to activate the atom-ide-debugger package

### ISSUE THREAD

**Issue by charludo** [atom-ide-community/atom-ide-debugger#10]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: linux 5.9.10-arch1-1
**Thrown From**: [atom-ide-debugger](https://github.com/atom-ide-community/atom-ide-debugger) package 0.0.3

### Stack Trace

Failed to activate the atom-ide-debugger package

```
At The expression evaluated to a falsy value:

  (0, _assert.default)(oldElem.constructor.name === 'ReactMountRootElement')


AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: The expression evaluated to a falsy value:

  (0, _assert.default)(oldElem.constructor.name === 'ReactMountRootElement')

    at /packages/atom-ide-console/node_modules/@atom-ide-community/nuclide-commons-ui/ReactMountRootElement.js:88:23)
    at /packages/atom-ide-console/node_modules/@atom-ide-community/nuclide-commons-ui/ReactMountRootElement.js:95:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:121:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:255:23)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (/usr/lib/atom/src/native-compile-cache.js:68:27)
    at /packages/atom-ide-console/node_modules/@atom-ide-community/nuclide-commons-ui/renderReactRoot.js:10:53)
    at /packages/atom-ide-console/node_modules/@atom-ide-community/nuclide-commons-ui/renderReactRoot.js:40:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:121:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:255:23)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (/usr/lib/atom/src/native-compile-cache.js:68:27)
    at /packages/atom-ide-debugger/dist/main.js:54:24)
    at /packages/atom-ide-debugger/dist/main.js:930:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:121:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:255:23)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (/usr/lib/atom/src/native-compile-cache.js:68:27)
    at Package.requireMainModule (/usr/lib/atom/src/package.js:907:27)
    at Package.activateNow (/usr/lib/atom/src/package.js:231:34)
    at /usr/lib/atom/src/package.js:1058:18
    at Function.simpleDispatch (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:64:14)
    at Emitter.emit (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:257:28)
    at PackageManager.triggerDeferredActivationHooks (/usr/lib/atom/src/package-manager.js:824:34)
    at /usr/lib/atom/src/package-manager.js:753:12
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-browsersync 0.2.0 
atom-ide-base 2.1.1 
atom-ide-console 0.0.0 
atom-ide-debugger 0.0.3 
atom-ide-ui 0.13.0 
atom-live-server 2.3.0 
atom-runner 2.7.1 
atom-sass 0.4.0 
atom-twig 4.2.0 
autoclose-html 0.23.0 
autocomplete-python 1.16.0 
busy-signal 2.0.1 
file-icons 2.1.44 
git-time-machine 2.1.0 
ide-python 1.6.2 
ide-yaml 0.7.1 
intentions 1.1.5 
kite 0.196.0 
linter 3.1.1 
linter-pylint 2.1.1 
linter-spell 0.15.0 
linter-ui-default 2.1.5 
minimap 4.35.4 
pigments 0.40.6 
project-viewer 1.4.0 
python-indent 1.2.6 
python-tools 0.6.9 
remote-sync 4.1.8 
script 3.26.0 
terminal-plus 0.14.5 
```

**Comment by aminya** [comment]
Similar to https://github.com/atom-ide-community/atom-ide-debugger/issues/9

atom-ide-ui is deprecated. You should use `atom-ide-base` only. 

Here I think there is a conflict between the two.

**Comment by haroldosales** [comment]
thank  you,  resolved  :+1:
