### ISSUE TITLE
Uncaught TypeError: call.getFileName is not a function

### ISSUE THREAD

**Issue by millenium404** [atom-ide-community/atom-ide-debugger#44]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: Zorin OS
**Thrown From**: [atom-ide-debugger](https://github.com/atom-ide-community/atom-ide-debugger) package 0.0.3

### Stack Trace

Uncaught TypeError: call.getFileName is not a function

```
At assert.js:270

TypeError: call.getFileName is not a function
    at getErrMessage (assert.js:270:25)
    at innerOk (assert.js:361:17)
    at ok (assert.js:381:3)
    at DebuggerLayoutManager._overridePaneInitialHeight (/packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:113:25)
    at Object.onPaneResize (/packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:149:14)
    at /packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:354:24
    at Function.simpleDispatch (/snap/atom/282/usr/share/atom/resources/app/static/<embedded>:11:1186190)
    at Emitter.emit (/snap/atom/282/usr/share/atom/resources/app/static/<embedded>:11:1187631)
    at Pane.setFlexScale (/snap/atom/282/usr/share/atom/resources/app/static/<embedded>:11:456811)
    at Pane.split (/snap/atom/282/usr/share/atom/resources/app/static/<embedded>:11:468012)
    at Pane.splitDown (/snap/atom/282/usr/share/atom/resources/app/static/<embedded>:11:467717)
    at DebuggerLayoutManager._appendItemToDock (/packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:325:20)
    at /packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:632:14
    at Array.forEach (<anonymous>)
    at DebuggerLayoutManager.showDebuggerViews (/packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:606:181)
    at /packages/atom-ide-debugger/dist/main.js:412:24)
    at CommandRegistry.handleCommandEvent (/snap/atom/282/usr/share/atom/resources/app/static/<embedded>:11:352215)
    at CommandRegistry.dispatch (/snap/atom/282/usr/share/atom/resources/app/static/<embedded>:11:350690)
    at /packages/atom-ide-debugger/dist/main.js:427:21)
    at CommandRegistry.handleCommandEvent (/snap/atom/282/usr/share/atom/resources/app/static/<embedded>:11:352215)
    at CommandRegistry.dispatch (/snap/atom/282/usr/share/atom/resources/app/static/<embedded>:11:350690)
    at AtomEnvironment.dispatchApplicationMenuCommand (/snap/atom/282/usr/share/atom/resources/app/static/<embedded>:1:786865)
    at EventEmitter.t (/snap/atom/282/usr/share/atom/resources/app/static/<embedded>:1:794836)
    at EventEmitter.emit (events.js:223:5)
    at Object.onMessage (electron/js2c/renderer_init.js:115:818)
```

### Commands

```
     -4:25.4.0 outline:show-call-hierarchy (atom-workspace.workspace.scrollbars-visible-always.theme-dark-one-dark-syntax.theme-nv-dark-ui)
  2x -4:00.3.0 linter-ui-default:toggle-panel (atom-workspace.workspace.scrollbars-visible-always.theme-dark-one-dark-syntax.theme-nv-dark-ui)
     -3:40.2.0 go-to-line:toggle (atom-text-editor.editor.is-focused)
     -2:50.6.0 linter-ui-default:toggle-panel (atom-workspace.workspace.scrollbars-visible-always.theme-dark-one-dark-syntax.theme-nv-dark-ui)
     -2:19.9.0 core:copy (div#linter-panel.)
     -1:12.7.0 console:toggle (input.hidden-input)
     -0:15.3.0 window:reset-font-size (input.hidden-input)
     -0:03.7.0 debugger:toggle (input.hidden-input)
     -0:03.7.0 debugger:show (atom-workspace.workspace.scrollbars-visible-always.theme-dark-one-dark-syntax.theme-nv-dark-ui)
```

### Non-Core Packages

```
atom-ide-base 3.4.0 
atom-ide-code-format 1.0.3 
atom-ide-console 0.0.2 
atom-ide-datatip 0.25.0 
atom-ide-debugger 0.0.3 
atom-ide-definitions 0.4.2 
atom-ide-hyperclick 1.0.11 
atom-ide-markdown-service 2.1.0 
atom-ide-outline 3.2.0 
atom-ide-signature-help 0.16.0 
atom-material-syntax 1.0.8 
autocomplete-python 1.17.1 
autosave-onchange 1.5.1 
busy-signal 2.0.1 
dark-one-dark-syntax 2.3.0 
dark-plus-syntax 2.5.0 
dracula-syntax 3.0.2 
ide-python 1.9.7 
intentions 2.1.1 
linter 3.4.0 
linter-ui-default 3.4.1 
nv-dark-ui 3.0.8 
seti-ui 1.11.0 
```

**Comment by charludo** [comment]
Same issue here. Did you find a solution? I'm also having the same error for the ide-python package.
