### ISSUE TITLE
Uncaught TypeError: You provided an invalid object where a stream was expected. You can provide a...

### ISSUE THREAD

**Issue by Jamesjin18** [atom-ide-community/atom-ide-debugger#7]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: Unknown Windows version
**Thrown From**: [atom-ide-debugger](https://github.com/atom-ide-community/atom-ide-debugger) package 0.0.2

### Stack Trace

Uncaught TypeError: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.

```
At C:\Users\maman\.atom\packages\atom-ide-debugger\node_modules\rxjs-compat\bundles\rxjs-compat.umd.min.js:42

TypeError: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
    at Object.subscribeToResult (/packages/ide-python/node_modules/rxjs/util/subscribeToResult.js:74:27)
    at MergeMapSubscriber._innerSub (/packages/ide-python/node_modules/rxjs/operators/mergeMap.js:132:38)
    at MergeMapSubscriber._tryNext (/packages/ide-python/node_modules/rxjs/operators/mergeMap.js:129:14)
    at MergeMapSubscriber._next (/packages/ide-python/node_modules/rxjs/operators/mergeMap.js:112:18)
    at MergeMapSubscriber.Subscriber.next (/packages/ide-python/node_modules/rxjs/Subscriber.js:93:18)
    at ArrayObservable._subscribe (/packages/ide-python/node_modules/rxjs/observable/ArrayObservable.js:114:28)
    at ArrayObservable.Observable._trySubscribe (/packages/ide-python/node_modules/rxjs/Observable.js:172:25)
    at ArrayObservable.Observable.subscribe (/packages/ide-python/node_modules/rxjs/Observable.js:160:93)
    at MergeMapOperator.call (/packages/ide-python/node_modules/rxjs/operators/mergeMap.js:87:23)
    at Observable.subscribe (/packages/ide-python/node_modules/rxjs/Observable.js:157:22)
    at b._subscribe (/packages/ide-python/node_modules/@atom-ide-community/nuclide-commons/observable.js:421:37)
    at b._trySubscribe (/packages/atom-ide-debugger/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:98:369)
    at b.subscribe (/packages/atom-ide-debugger/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:98:154)
    at /packages/atom-ide-debugger/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:139:187
    at /packages/atom-ide-debugger/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:52:239)
    at a._innerSub (/packages/atom-ide-debugger/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:143:252)
    at a._tryNext (/packages/atom-ide-debugger/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:143:140)
    at a._next (/packages/atom-ide-debugger/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:142:475)
    at a.next (/packages/atom-ide-debugger/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:92:214)
    at b._subscribe (/packages/atom-ide-debugger/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:120:475)
    at b._trySubscribe (/packages/atom-ide-debugger/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:98:369)
    at b.subscribe (/packages/atom-ide-debugger/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:98:154)
    at b.call (/packages/atom-ide-debugger/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:142:158)
    at b.subscribe (/packages/atom-ide-debugger/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:98:28)
    at /packages/atom-ide-debugger/dist/BreakpointDisplayController.js:70:61)
    at BreakpointManager._handleTextEditor (/packages/atom-ide-debugger/dist/BreakpointManager.js:52:26)
    at ~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:429444
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:1190051)
    at Emitter.emit (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:1191492)
    at ~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:427547
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-base 2.1.1 
atom-ide-debugger 0.0.2 
html-to-css 0.2.2 
ide-python 1.6.0 
```

**Comment by aminya** [comment]
What is the reproduction steps?
