### ISSUE TITLE
Failed to activate the atom-ide-debugger package

### ISSUE THREAD

**Issue by mjskier** [atom-ide-community/atom-ide-debugger#9]
[Enter steps to reproduce:]

1. Just selecting the itom-ide-debugger package to install

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: Linux Mint
**Thrown From**: [atom-ide-debugger](https://github.com/atom-ide-community/atom-ide-debugger) package 0.0.3

### Stack Trace

Failed to activate the atom-ide-debugger package

```
At The expression evaluated to a falsy value:

  (0, _assert.default)(oldElem.constructor.name === 'ReactMountRootElement')


AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: The expression evaluated to a falsy value:

  (0, _assert.default)(oldElem.constructor.name === 'ReactMountRootElement')

    at /packages/atom-ide-debugger/node_modules/@atom-ide-community/nuclide-commons-ui/ReactMountRootElement.js:88:23)
    at /packages/atom-ide-debugger/node_modules/@atom-ide-community/nuclide-commons-ui/ReactMountRootElement.js:95:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146814)
    at /packages/atom-ide-debugger/node_modules/@atom-ide-community/nuclide-commons-ui/renderReactRoot.js:10:53)
    at /packages/atom-ide-debugger/node_modules/@atom-ide-community/nuclide-commons-ui/renderReactRoot.js:40:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146814)
    at /packages/atom-ide-debugger/dist/main.js:54:24)
    at /packages/atom-ide-debugger/dist/main.js:930:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:16:16)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:1:696928)
    at Package.requireMainModule (/usr/share/atom/resources/app/static/<embedded>:11:3578827)
    at Package.activateNow (/usr/share/atom/resources/app/static/<embedded>:11:3566811)
    at /usr/share/atom/resources/app/static/<embedded>:14:2607
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1190051)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1191492)
    at /usr/share/atom/resources/app/static/<embedded>:11:383812
    at Set.forEach (<anonymous>)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/static/<embedded>:11:383774)
    at /usr/share/atom/resources/app/static/<embedded>:11:916621
    at r (/usr/share/atom/resources/app/static/<embedded>:11:911227)
    at s (/usr/share/atom/resources/app/static/<embedded>:14:1134638)
```

### Commands

```
     -7:24.7.0 ask-stack:ask-question (input.hidden-input)
     -6:47.7.0 application:open-file (div.panels-item)
  4x -6:25.2.0 find-references:activate (div.line)
     -4:49 emacs-plus:kill-word (input.hidden-input)
     -4:46.5.0 core:undo (input.hidden-input)
  2x -3:58.1.0 golang:godef (span.syntax--entity.syntax--name.syntax--function)
     -2:26.8.0 debugger:show-launch-dialog (atom-pane.pane.active)
     -1:38.6.0 core:cancel (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
ask-stack 2.2.0 
atom-beautify 0.33.4 
atom-ide-debugger 0.0.3 
atom-ide-ui 0.13.0 
emacs-plus 0.12.0 
file-icons 2.1.44 
go-debug 1.7.0 
go-plus 6.1.0 
go-signature-statusbar 1.2.3 
todo 0.6.0 
```

**Comment by aminya** [comment]
Why don't you have atom-ide-console installed? 

atom-ide-ui is deprecated. You should use atom-ide-base instead.

**Comment by mjskier** [comment]
Thanks for the deprecation info.
atom-ide-ui doesn't show as deprecated in my version of Atom (1.51.0)

**Comment by aminya** [comment]
It does not show inside Atom yet. I need to make a PR to add the deprecation warning.

Install `atom-ide-base` instead.

The repo was archived 2 years ago.
https://github.com/facebookarchive/atom-ide-ui

**Comment by mjskier** [comment]
Thank you Amin.
